---
abstract: 'Simple LDAP authentication'
author:
  - 'Christian Hansen C<chansen@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Authen-Simple-LDAP
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Authen::Simple: 0
  Net::LDAP: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/chansen/p5-authen-simple-ldap
version: 0.3
